import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const memory=new Map();global.localStorage={getItem:k=>memory.has(k)?memory.get(k):null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};global.window=global;
vm.runInThisContext(fs.readFileSync('js/storage.js','utf8'));vm.runInThisContext(fs.readFileSync('js/recommendation.js','utf8'));
const defaults={cityPriority:{哈尔滨:6,北京:5,'东北其他':1},minSalary:0,acceptUnknownSalary:true,schoolTypes:{public:true,private:true,international:true,other:true},jobTypes:{漫画:true},acceptEnglish:false,acceptIB:false,acceptALevel:false,acceptIGCSE:false,topPriority:'city'};
RadarStore.savePreferences(defaults);assert.equal(RadarStore.getPreferences({}).cityPriority.哈尔滨,6,'preferences persist');
localStorage.setItem('jobstate:legacy-id',JSON.stringify({application_status:'已投递'}));assert.equal(RadarStore.getJobState('legacy-id').application_status,'已投递','legacy state migrates');
RadarStore.saveJobState('stable-id',{favorite:true});assert.equal(RadarStore.getJobState('stable-id').favorite,true,'job state persists by stable id');
const job={job_title:'漫画教师',job_category:'美术教师',match_reasons:['漫画'],hard_blockers:[],job_status:'verify',match_score:80,city:'哈尔滨',school_type:'民办学校',salary_min:9000,english_required:false};
const steady=RadarRecommendation.score(job,defaults),changed=RadarRecommendation.score(job,{...defaults,cityPriority:{哈尔滨:1,北京:6,'东北其他':1},minSalary:15000,topPriority:'salary'});assert.notEqual(steady,changed,'recommendation changes with preferences');assert.equal(job.match_score,80,'objective match score is unchanged');
console.log('OK: storage persistence, legacy migration, and preference scoring tests passed.');
