#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'
EVIDENCE={
 'official_primary':'https://www.hlj.gov.cn/hlj/c107858/202212/c00_31511763.shtml',
 'official_high':'https://www.hlj.gov.cn/hlj/c107858/202605/c00_31943619.shtml',
 'private':'https://finance.sina.com.cn/wm/2026-05-16/doc-inhyassp4488646.shtml',
 'directory':'https://www.114city.com/harbin/xuexiao/all-all'}
harbin=[
('哈尔滨市继红小学校','南岗区','小学','公办','official_primary'),('哈尔滨市花园小学校','南岗区','小学','公办','official_primary'),('哈尔滨市师范附属小学校','南岗区','小学','公办','official_primary'),('哈尔滨市铁岭小学校','南岗区','小学','公办','official_primary'),('哈尔滨市复华小学校','南岗区','小学','公办','official_primary'),('哈尔滨市虹桥第一小学校','南岗区','小学','公办','official_primary'),('哈尔滨市虹桥第二小学校','南岗区','小学','公办','official_primary'),('哈尔滨市闽江小学校','南岗区','小学','公办','official_primary'),('哈尔滨市红岩小学校','南岗区','小学','公办','official_primary'),('哈尔滨市奋斗小学校','南岗区','小学','公办','official_primary'),('哈尔滨市医大逸夫小学校','南岗区','小学','公办','official_primary'),('哈尔滨市马家沟小学校','南岗区','小学','公办','official_primary'),('哈尔滨市育红小学校','南岗区','小学','公办','official_primary'),('哈尔滨市团结小学校','南岗区','小学','公办','official_primary'),('哈尔滨市雷锋小学校','南岗区','小学','公办','official_primary'),('哈尔滨市征仪路学校','南岗区','九年一贯制','公办','official_primary'),
('哈尔滨市第一中学校','道里区','高中','公办','official_high'),('哈尔滨市第三中学校','南岗区/道里区','高中','公办','official_high'),('哈尔滨市第六中学校','香坊区','高中','公办','official_high'),('哈尔滨市第九中学校','香坊区/松北区','高中','公办','official_high'),('哈尔滨市第二十四中学校','平房区','高中','公办','official_high'),('哈尔滨师范大学附属中学','南岗区','高中','公办','official_high'),('黑龙江省实验中学','南岗区','高中','公办','official_high'),('哈尔滨市第十三中学校','南岗区','高中','公办','directory'),('哈尔滨市第十四中学校','道里区','高中','公办','directory'),('哈尔滨市第十一中学校','香坊区','高中','公办','directory'),('哈尔滨市第十二中学校','道外区','高中','公办','directory'),('哈尔滨市第十八中学校','道里区','高中','公办','directory'),('哈尔滨市第四中学校','道外区','高中','公办','directory'),('哈尔滨市第五中学校','道里区','高中','公办','directory'),('哈尔滨市第五十九中学校','香坊区','初中','公办','directory'),('哈尔滨市第六十九中学校','南岗区','初中','公办','directory'),('哈尔滨市第七十三中学校','南岗区','初中','公办','directory'),('哈尔滨市第一二二中学校','香坊区','初中','公办','directory'),('哈尔滨市第一六三中学校','南岗区','初中','公办','directory'),('哈尔滨市第一六二中学校','平房区','高中','公办','directory'),('哈尔滨市第四十七中学校','南岗区','初中','公办','directory'),('哈尔滨市第四十九中学校','南岗区','初中','公办','directory'),('哈尔滨市第五十二中学校','香坊区','初中','公办','directory'),('哈尔滨市第五十八中学校','道外区','高中','公办','directory'),('哈尔滨市第十七中学校','南岗区','初中','公办','directory'),('哈尔滨市第三十九中学校','香坊区','初中','公办','directory'),('哈尔滨市第一〇一中学校','香坊区','高中','公办','directory'),('哈尔滨市第九十七中学校','道里区','初中','公办','directory'),('哈尔滨市宝宇六十九中学校','道外区','初中','公办','directory'),
('哈尔滨工业大学附属中学校','南岗区','完全中学','民办','private'),('哈尔滨市松雷中学校','南岗区','完全中学','民办','private'),('哈尔滨德强学校','香坊区','十二年一贯制','民办','private'),('哈尔滨市中实学校','南岗区','完全中学','民办','private'),('哈尔滨市剑桥第三中学校','香坊区','完全中学','民办','private'),('哈尔滨市美佳外国语学校','松北区','九年一贯制','民办/外国语','private'),('哈尔滨顺迈学校','松北区','十二年一贯制','民办','private'),('哈尔滨市秋实学校','道里区','九年一贯制','民办','private'),('哈尔滨市万邦学校','松北区','十二年一贯制','民办','private'),('哈尔滨市荣智学校','道外区','九年一贯制','民办','private'),('哈尔滨新区现代高中','松北区','高中','民办','directory'),('哈尔滨市南之岗高级中学','南岗区','高中','民办','directory'),('哈尔滨市松北区东方文化艺术学校','松北区','艺术教育/艺考','民办','directory'),('哈尔滨市现代艺术设计职业技术学校','南岗区','中职/艺术','民办','directory'),('哈尔滨市华艺舞蹈艺术中等职业学校','松北区','中职/艺术','民办','directory')]
harbin_data=[{'id':f'hrb-school-{i+1:03}','school_name':n,'city':'哈尔滨','district':d,'education_stage':stage,'school_type':typ,'official_url':None,'recruitment_url':None,'evidence_url':EVIDENCE[e],'verification_status':'真实学校名录/政府招生信息已交叉发现','monitoring_priority':'S','last_checked':None,'last_success':None,'jobs_discovered':0,'queries_executed':0} for i,(n,d,stage,typ,e) in enumerate(harbin)]
city_schools={
'北京':['北京学校','北京市育英学校','北京第一实验学校','北京第三实验学校','北京第四实验学校','北京市十一学校','北京一零一中学','北京市三帆中学','北京师范大学第二附属中学','北京市鼎石学校','北京德威英国国际学校','北京顺义国际学校'],
'沈阳':['东北育才学校','辽宁省实验中学','沈阳市第二中学','沈阳市第一二〇中学','沈阳市艺术幼儿师范学校','鲁迅美术学院附属中等美术学校','沈阳翼众东北美术学校','沈阳市翔宇中学'],
'大连':['大连市第二十四中学','大连育明高级中学','大连市第八中学','大连枫叶国际学校','大连华美学校','大连文谷高级中学','大连弘远美术高级中学','东北师范大学大连保税区实验学校'],
'长春':['东北师范大学附属中学','吉林省实验中学','长春市十一高中','长春市第二实验中学','长春市清蒲中学','长春市柏辰艺术中学','长春市笔翼教育培训学校','长春科技学院']}
city_data=[]
for city,names in city_schools.items():
 for i,n in enumerate(names): city_data.append({'id':f'{city}-school-{i+1:02}','school_name':n,'city':city,'district':None,'school_type':'未细分','official_url':None,'recruitment_url':None,'evidence_url':None,'verification_status':'Deep Search 公开结果发现，待补官网','monitoring_priority':'A','last_checked':None,'last_success':None,'jobs_discovered':0,'queries_executed':0})
official=[
('哈尔滨市教育局招聘系统','哈尔滨',None,'教育局','https://rencaizhaopin.hrbeduy.com/','A'),('哈尔滨市政府信息','哈尔滨',None,'政府','https://www.harbin.gov.cn/','A'),('哈尔滨市政务服务网','哈尔滨',None,'政府/区级入口','https://zwfw.harbin.gov.cn/','A'),('南岗区教育局政务入口','哈尔滨','南岗区','区教育局','https://zwfw.harbin.gov.cn/hz_root/bstype/grall?vmcityout=ngq','A'),('道里区政府','哈尔滨','道里区','区政府','https://www.hrbdl.gov.cn/','A'),('道外区政府','哈尔滨','道外区','区政府','https://www.hrbdw.gov.cn/','A'),('香坊区政务服务网','哈尔滨','香坊区','区教育/人社','https://zwfw.harbin.gov.cn/hz_root/map/minglu?vmcityout=xfq','A'),('松北区政府/哈尔滨新区','哈尔滨','松北区','区政府','https://www.songbei.gov.cn/','A'),('平房区政府','哈尔滨','平房区','区政府','https://www.hrbpf.gov.cn/','A'),('呼兰区政务服务网','哈尔滨','呼兰区','区教育/人社','https://zwfw.harbin.gov.cn/hz_root/oneQY/bsbqr?vmcityout=hlq','A'),('黑龙江省事业单位公开招聘平台','哈尔滨',None,'省级人社','https://hlj.zhaopin.com/','B'),
('北京市人社局事业单位招聘','北京',None,'人社局','https://rsj.beijing.gov.cn/xxgk/gkzp/index.html','A'),('首都之窗事业单位招聘','北京',None,'政府','https://www.beijing.gov.cn/gongkai/rsxx/sydwzp/index.html','A'),('沈阳市教育局','沈阳',None,'教育局','https://jyj.shenyang.gov.cn/','A'),('沈阳市人社局','沈阳',None,'人社局','https://rsj.shenyang.gov.cn/','A'),('大连市教育局','大连',None,'教育局','https://edu.dl.gov.cn/','A'),('大连市人社局','大连',None,'人社局','https://rsj.dl.gov.cn/','A'),('长春市教育局','长春',None,'教育局','https://jyj.changchun.gov.cn/','A'),('长春市人社局通知公告','长春',None,'人社局','https://ccrs.changchun.gov.cn/ywdt/tzgg/','A')]
official_data=[{'id':f'official-{i+1:03}','source_name':n,'city':c,'district':d,'source_type':t,'url':u,'last_checked':None,'last_success':None,'jobs_discovered':0,'automation_level':a} for i,(n,c,d,t,u,a) in enumerate(official)]
recruit=[('BOSS直聘','招聘平台','https://www.zhipin.com/','C'),('智联招聘','招聘平台','https://www.zhaopin.com/','C'),('猎聘','招聘平台','https://www.liepin.com/','C'),('万行教师人才网','教师招聘','https://www.job10000.com/','C'),('高校人才网','教师招聘/聚合','https://www.gaoxiaojob.com/','B'),('教师招聘网 job910','教师招聘/聚合','https://www.job910.com/','B'),('粉笔资讯','事业单位聚合','https://www.fenbi.com/','B'),('全国事业单位招聘网','事业单位聚合','https://qgsydw.com/','B'),('Nord Anglia Careers','国际学校招聘','https://careers.nordangliaeducation.com/','B'),('eChinaCareers','国际招聘平台','https://echinacareers.com/','B'),('高校就业信息网集合','高校就业','https://www.ncss.cn/','B'),('Bing News RSS','公开搜索','https://www.bing.com/news/search','B')]
recruit_data=[{'id':f'recruit-{i+1:02}','source_name':n,'source_type':t,'url':u,'automation_level':a,'last_checked':None,'last_success':None,'jobs_discovered':0,'manual_required':a=='C'} for i,(n,t,u,a) in enumerate(recruit)]
for name,data in [('harbin-schools.json',harbin_data),('city-schools.json',city_data),('official-sources.json',official_data),('recruitment-sources.json',recruit_data)]: (DATA/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n','utf-8')
print(json.dumps({'harbin_schools':len(harbin_data),'other_city_schools':len(city_data),'official_sources':len(official_data),'recruitment_sources':len(recruit_data)},ensure_ascii=False))
